// FILE: config.cpp
#include "config.h"

// Default constructor implementation
Config::Config() :
    // --- Neuron Properties ---
    RESTING_POTENTIAL_MV(-70.0),
    SPIKE_THRESHOLD_MV(-55.0),
    MEMBRANE_TIME_CONSTANT_MS(20.0),
    REFRACTORY_PERIOD_MS(3.0),
    // --- Izhikevich Model Parameters ---
    IZH_A(0.02), IZH_B(0.2), IZH_C(-65.0), IZH_D(8.0),
    IZH_SPIKE_PEAK_MV(30.0),
    // --- Synapse Properties ---
    E_EXCITATORY_MV(0.0), E_INHIBITORY_MV(-80.0),
    EXCITATORY_CONDUCTANCE_SCALE_NS(1.0), INHIBITORY_CONDUCTANCE_SCALE_NS(1.5),
    SYNAPTIC_TIME_CONSTANT_MS(5.0),
    // --- Short-Term Plasticity (STP) Properties ---
    STP_U(0.45), STP_TAU_FACIL_MS(50.0), STP_TAU_DECAY_MS(750.0),
    // --- Long-Term Plasticity (STDP) Properties ---
    STDP_WINDOW_MS(20.0),
    LTP_RATE(0.15),                           
    LTD_RATE(-0.15),                     
    // --- Reward-Modulated STDP Properties ---
    DOPAMINE_BASE_LEVEL(0.001), DOPAMINE_DECAY_HALF_LIFE_MS(300.0),
    ELIGIBILITY_TRACE_DECAY_TAU_MS(400.0),
    PUNISHMENT_TRACE_DECAY_TAU_MS(400.0),
    // --- Learning & Weight Properties ---
    LEARNING_RATE(10.0),                   
    PUNISHMENT_LEARNING_RATE(15.0),         
    MAX_WEIGHT(20.0),
    INITIAL_WEIGHT_MIN(4.0),                    
    INITIAL_WEIGHT_MAX(6.0),                    
    // --- Homeostatic Plasticity Properties ---
    HOMEOSTASIS_TAU_MS(1000.0),                 
    TARGET_FIRING_RATE_HZ(1.0),
    HOMEOSTASIS_ADAPTATION_RATE(0.0005),          
    HOMEOSTASIS_MIN_THRESHOLD_MARGIN_MV(5.0),
    // --- Simulation Properties ---
    NOISE_STD_DEV_NA(0.5),                       
    SIMULATION_SEED(std::nullopt),              
    // --- Experiment-specific Properties ---
    TRAINING_EPOCHS(30),
    REVERSAL_EPOCHS(60),                        
    TIME_STEP(0.1),
    TRIAL_DURATION_MS(150.0),
    STIMULUS_DURATION_MS(50.0),
    STIMULUS_POISSON_RATE_HZ(35.0),
    STIMULUS_PULSE_DURATION_MS(2.0),
    ITI_MS(1000.0),
    STIMULATION_CURRENT_NA(50.0),             
    LOG_INTERVAL_MS(10.0),
    REWARD_AMOUNT_SUCCESS(1.0),
    REINFORCE_AMOUNT_OMISSION(0.15),
    PUNISH_AMOUNT_MISTAKE(5.0),                  
    PUNISHMENT_TAG_AMOUNT(1.0),
    PUNISHMENT_TAG_WINDOW_MS(100.0),            
    UNLEARNING_TAG_AMOUNT(0.25),

    // --- Structural Plasticity Properties ---
    ENABLE_STRUCTURAL_PLASTICITY(true),
    STRUCTURAL_UPDATE_INTERVAL_MS(2000.0),       
    PRUNING_WEIGHT_THRESHOLD(0.1),
    PRUNING_PUNISHMENT_THRESHOLD(2.0),           
    SPROUTING_ACTIVITY_THRESHOLD_HZ(0.5),        
    SPROUTING_MAX_DISTANCE(15.0),                 
    NEW_CONNECTION_PROBABILITY(0.25),
    NEW_SYNAPSE_INITIAL_WEIGHT(1.0)
{}


// Implementation for loading from JSON
#define CONFIG_LOAD_PARAM(param) c.param = j.value(#param, c.param);

Config Config::from_json(const json& j) {
    Config c; // Start with default values
    CONFIG_LOAD_PARAM(RESTING_POTENTIAL_MV)
    CONFIG_LOAD_PARAM(SPIKE_THRESHOLD_MV)
    CONFIG_LOAD_PARAM(MEMBRANE_TIME_CONSTANT_MS)
    CONFIG_LOAD_PARAM(REFRACTORY_PERIOD_MS)
    CONFIG_LOAD_PARAM(IZH_A)
    CONFIG_LOAD_PARAM(IZH_B)
    CONFIG_LOAD_PARAM(IZH_C)
    CONFIG_LOAD_PARAM(IZH_D)
    CONFIG_LOAD_PARAM(IZH_SPIKE_PEAK_MV)
    CONFIG_LOAD_PARAM(E_EXCITATORY_MV)
    CONFIG_LOAD_PARAM(E_INHIBITORY_MV)
    CONFIG_LOAD_PARAM(EXCITATORY_CONDUCTANCE_SCALE_NS)
    CONFIG_LOAD_PARAM(INHIBITORY_CONDUCTANCE_SCALE_NS)
    CONFIG_LOAD_PARAM(SYNAPTIC_TIME_CONSTANT_MS)
    CONFIG_LOAD_PARAM(STP_U)
    CONFIG_LOAD_PARAM(STP_TAU_FACIL_MS)
    CONFIG_LOAD_PARAM(STP_TAU_DECAY_MS)
    CONFIG_LOAD_PARAM(STDP_WINDOW_MS)
    CONFIG_LOAD_PARAM(LTP_RATE)
    CONFIG_LOAD_PARAM(LTD_RATE)
    CONFIG_LOAD_PARAM(DOPAMINE_BASE_LEVEL)
    CONFIG_LOAD_PARAM(DOPAMINE_DECAY_HALF_LIFE_MS)
    CONFIG_LOAD_PARAM(ELIGIBILITY_TRACE_DECAY_TAU_MS)
    CONFIG_LOAD_PARAM(PUNISHMENT_TRACE_DECAY_TAU_MS)
    CONFIG_LOAD_PARAM(LEARNING_RATE)
    CONFIG_LOAD_PARAM(PUNISHMENT_LEARNING_RATE)
    CONFIG_LOAD_PARAM(MAX_WEIGHT)
    CONFIG_LOAD_PARAM(INITIAL_WEIGHT_MIN)
    CONFIG_LOAD_PARAM(INITIAL_WEIGHT_MAX)
    CONFIG_LOAD_PARAM(HOMEOSTASIS_TAU_MS)
    CONFIG_LOAD_PARAM(TARGET_FIRING_RATE_HZ)
    CONFIG_LOAD_PARAM(HOMEOSTASIS_ADAPTATION_RATE)
    CONFIG_LOAD_PARAM(HOMEOSTASIS_MIN_THRESHOLD_MARGIN_MV)
    CONFIG_LOAD_PARAM(NOISE_STD_DEV_NA)
    if (j.contains("SIMULATION_SEED") && !j["SIMULATION_SEED"].is_null()) {
        c.SIMULATION_SEED = j.value("SIMULATION_SEED", 0u);
    }
    CONFIG_LOAD_PARAM(TRAINING_EPOCHS)
    if (j.contains("REVERSAL_EPOCHS") && !j["REVERSAL_EPOCHS"].is_null()) {
        c.REVERSAL_EPOCHS = j.value("REVERSAL_EPOCHS", 30);
    } else {
        c.REVERSAL_EPOCHS = std::nullopt; // Disable if null or not present
    } 
    CONFIG_LOAD_PARAM(TIME_STEP)
    CONFIG_LOAD_PARAM(TRIAL_DURATION_MS)
    CONFIG_LOAD_PARAM(STIMULUS_DURATION_MS)
    CONFIG_LOAD_PARAM(STIMULUS_POISSON_RATE_HZ)
    CONFIG_LOAD_PARAM(STIMULUS_PULSE_DURATION_MS)
    CONFIG_LOAD_PARAM(ITI_MS)
    CONFIG_LOAD_PARAM(STIMULATION_CURRENT_NA)
    CONFIG_LOAD_PARAM(LOG_INTERVAL_MS)
    CONFIG_LOAD_PARAM(REWARD_AMOUNT_SUCCESS)
    CONFIG_LOAD_PARAM(REINFORCE_AMOUNT_OMISSION)
    CONFIG_LOAD_PARAM(PUNISH_AMOUNT_MISTAKE)
    CONFIG_LOAD_PARAM(PUNISHMENT_TAG_AMOUNT)
    CONFIG_LOAD_PARAM(PUNISHMENT_TAG_WINDOW_MS)
    CONFIG_LOAD_PARAM(UNLEARNING_TAG_AMOUNT)
    CONFIG_LOAD_PARAM(ENABLE_STRUCTURAL_PLASTICITY)
    CONFIG_LOAD_PARAM(STRUCTURAL_UPDATE_INTERVAL_MS)
    CONFIG_LOAD_PARAM(PRUNING_WEIGHT_THRESHOLD)
    CONFIG_LOAD_PARAM(PRUNING_PUNISHMENT_THRESHOLD)
    CONFIG_LOAD_PARAM(SPROUTING_ACTIVITY_THRESHOLD_HZ)
    CONFIG_LOAD_PARAM(SPROUTING_MAX_DISTANCE)
    CONFIG_LOAD_PARAM(NEW_CONNECTION_PROBABILITY)
    CONFIG_LOAD_PARAM(NEW_SYNAPSE_INITIAL_WEIGHT)
    return c;
}

#undef CONFIG_LOAD_PARAM

// Implementation for converting to JSON
#define CONFIG_SAVE_PARAM(param) j[#param] = param;

json Config::to_json() const {
    json j;
    CONFIG_SAVE_PARAM(RESTING_POTENTIAL_MV)
    CONFIG_SAVE_PARAM(SPIKE_THRESHOLD_MV)
    CONFIG_SAVE_PARAM(MEMBRANE_TIME_CONSTANT_MS)
    CONFIG_SAVE_PARAM(REFRACTORY_PERIOD_MS)
    CONFIG_SAVE_PARAM(IZH_A)
    CONFIG_SAVE_PARAM(IZH_B)
    CONFIG_SAVE_PARAM(IZH_C)
    CONFIG_SAVE_PARAM(IZH_D)
    CONFIG_SAVE_PARAM(IZH_SPIKE_PEAK_MV)
    CONFIG_SAVE_PARAM(E_EXCITATORY_MV)
    CONFIG_SAVE_PARAM(E_INHIBITORY_MV)
    CONFIG_SAVE_PARAM(EXCITATORY_CONDUCTANCE_SCALE_NS)
    CONFIG_SAVE_PARAM(INHIBITORY_CONDUCTANCE_SCALE_NS)
    CONFIG_SAVE_PARAM(SYNAPTIC_TIME_CONSTANT_MS)
    CONFIG_SAVE_PARAM(STP_U)
    CONFIG_SAVE_PARAM(STP_TAU_FACIL_MS)
    CONFIG_SAVE_PARAM(STP_TAU_DECAY_MS)
    CONFIG_SAVE_PARAM(STDP_WINDOW_MS)
    CONFIG_SAVE_PARAM(LTP_RATE)
    CONFIG_SAVE_PARAM(LTD_RATE)
    CONFIG_SAVE_PARAM(DOPAMINE_BASE_LEVEL)
    CONFIG_SAVE_PARAM(DOPAMINE_DECAY_HALF_LIFE_MS)
    CONFIG_SAVE_PARAM(ELIGIBILITY_TRACE_DECAY_TAU_MS)
    CONFIG_SAVE_PARAM(PUNISHMENT_TRACE_DECAY_TAU_MS)
    CONFIG_SAVE_PARAM(LEARNING_RATE)
    CONFIG_SAVE_PARAM(PUNISHMENT_LEARNING_RATE)
    CONFIG_SAVE_PARAM(MAX_WEIGHT)
    CONFIG_SAVE_PARAM(INITIAL_WEIGHT_MIN)
    CONFIG_SAVE_PARAM(INITIAL_WEIGHT_MAX)
    CONFIG_SAVE_PARAM(HOMEOSTASIS_TAU_MS)
    CONFIG_SAVE_PARAM(TARGET_FIRING_RATE_HZ)
    CONFIG_SAVE_PARAM(HOMEOSTASIS_ADAPTATION_RATE)
    CONFIG_SAVE_PARAM(HOMEOSTASIS_MIN_THRESHOLD_MARGIN_MV)
    CONFIG_SAVE_PARAM(NOISE_STD_DEV_NA)
    if (SIMULATION_SEED) j["SIMULATION_SEED"] = SIMULATION_SEED.value();
    else j["SIMULATION_SEED"] = nullptr;
    CONFIG_SAVE_PARAM(TRAINING_EPOCHS)
    if (REVERSAL_EPOCHS) { j["REVERSAL_EPOCHS"] = REVERSAL_EPOCHS.value(); }
    else { j["REVERSAL_EPOCHS"] = nullptr; }    
    CONFIG_SAVE_PARAM(TIME_STEP)
    CONFIG_SAVE_PARAM(TRIAL_DURATION_MS)
    CONFIG_SAVE_PARAM(STIMULUS_DURATION_MS)
    CONFIG_SAVE_PARAM(STIMULUS_POISSON_RATE_HZ)
    CONFIG_SAVE_PARAM(STIMULUS_PULSE_DURATION_MS)
    CONFIG_SAVE_PARAM(ITI_MS)
    CONFIG_SAVE_PARAM(STIMULATION_CURRENT_NA)
    CONFIG_SAVE_PARAM(LOG_INTERVAL_MS)
    CONFIG_SAVE_PARAM(REWARD_AMOUNT_SUCCESS)
    CONFIG_SAVE_PARAM(REINFORCE_AMOUNT_OMISSION)
    CONFIG_SAVE_PARAM(PUNISH_AMOUNT_MISTAKE)
    CONFIG_SAVE_PARAM(PUNISHMENT_TAG_AMOUNT)
    CONFIG_SAVE_PARAM(PUNISHMENT_TAG_WINDOW_MS)
    CONFIG_SAVE_PARAM(UNLEARNING_TAG_AMOUNT)
    CONFIG_SAVE_PARAM(ENABLE_STRUCTURAL_PLASTICITY)
    CONFIG_SAVE_PARAM(STRUCTURAL_UPDATE_INTERVAL_MS)
    CONFIG_SAVE_PARAM(PRUNING_WEIGHT_THRESHOLD)
    CONFIG_SAVE_PARAM(PRUNING_PUNISHMENT_THRESHOLD)
    CONFIG_SAVE_PARAM(SPROUTING_ACTIVITY_THRESHOLD_HZ)
    CONFIG_SAVE_PARAM(SPROUTING_MAX_DISTANCE)
    CONFIG_SAVE_PARAM(NEW_CONNECTION_PROBABILITY)
    CONFIG_SAVE_PARAM(NEW_SYNAPSE_INITIAL_WEIGHT)
    return j;
}

#undef CONFIG_SAVE_PARAM